// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOMPG-toLimrODGjI18UQd5yorAx4Sm7k',
    appId: '1:622823895967:web:5b8e17671a2a4a3c8643aa',
    messagingSenderId: '622823895967',
    projectId: 'comunidad-bochil',
    authDomain: 'comunidad-bochil.firebaseapp.com',
    storageBucket: 'comunidad-bochil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlnPk7vnSe81v5TjbEkyt58-qtSoB_jS0',
    appId: '1:622823895967:android:c38e605c957e52fc8643aa',
    messagingSenderId: '622823895967',
    projectId: 'comunidad-bochil',
    storageBucket: 'comunidad-bochil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZXFkfkO7vZeLILrSzI7p8mfwUSvukTpQ',
    appId: '1:622823895967:ios:d3347fa879de1c458643aa',
    messagingSenderId: '622823895967',
    projectId: 'comunidad-bochil',
    storageBucket: 'comunidad-bochil.firebasestorage.app',
    iosBundleId: 'com.example.comunidadBochil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZXFkfkO7vZeLILrSzI7p8mfwUSvukTpQ',
    appId: '1:622823895967:ios:d3347fa879de1c458643aa',
    messagingSenderId: '622823895967',
    projectId: 'comunidad-bochil',
    storageBucket: 'comunidad-bochil.firebasestorage.app',
    iosBundleId: 'com.example.comunidadBochil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOMPG-toLimrODGjI18UQd5yorAx4Sm7k',
    appId: '1:622823895967:web:8e11a35660bc98628643aa',
    messagingSenderId: '622823895967',
    projectId: 'comunidad-bochil',
    authDomain: 'comunidad-bochil.firebaseapp.com',
    storageBucket: 'comunidad-bochil.firebasestorage.app',
  );
}
